export const projects = [
  {
    title: 'React/CSS Gym Website',
    description: "Project based on React, CSS and a few libs. This project was deployed at Vercel. check it out, link below. React is a powerfull library and it uses JSX, a syntax extension to Javascript. JSX allows us to write HTML in React. JSX makes it easier to write and add HTML in React. The project is also complete responsive for mobile devices. ",
      image: '/images/1.png',
      tags: ['CSS', 'React', 'Node', 'Javascript'],
    source: 'https://react-gym-ebon.vercel.app',
    visit: 'https://react-gym-ebon.vercel.app',
    id: 0,
  },
  {
    title: 'E-Commerce Bag Store',
    description:"E-Commerce site builted with React and Material UI. It also uses react hooks such as useState and useContext. It's a responsive site and can be used on different screen sizes. I used Eslint e Prettier on the dev environment setup for this project. CSS was used with styled-components.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript', 'Material UI', 'Vite'],
    source: 'https://bag-store.vercel.app',
    visit: 'https://bag-store.vercel.app',
    id: 1,
  },
  {
    title: 'Hotel WebSite',
    description: "This is a hotel page example made with React, Next.js 13,  react-slick and react-popup. In this project, i used some features of Next.js 13 such as dynamic Routes and optimized Image component. I have added some animations on the first page with Framer-Motion.",
      image: '/images/4.png',
      tags: ['React', 'JavaScript', 'Next.js', 'Framer Motion'],
    source: 'https://golf-resort.vercel.app/',
    visit: 'https://golf-resort.vercel.app/',
    id: 2,
  },
  {
    title: 'Landing Page',
    description: "This is a landing page example made with React. In this project, i used MaterialUI lib. It was deployed at Vercel. Simple CSS with just one file to the whole project. The purpose of this project is to make an IT selling site course with all kinds of subscriptions available on it.",
    image: '/images/3.png',
    tags: ['JavaScript', 'Material UI'],
    source: 'https://cursos-para-ti.vercel.app',
    visit: 'https://cursos-para-ti.vercel.app',
    id: 3,
  },
    {
    title: 'Low-Code/No-Code',
    description: "This is an app made with PowerApps Plataform. It use power automate flows to send notifications to its users. The data is stored on sharepoint lists. Also it has a dashboard panel developed on PowerBI and embbedded on the app.",
    image: '/images/5.png',
    tags: ['PowerApp', 'Power Automate', 'PowerBI'],
    source: '',
    visit: '',
    id: 4,
  },
    {
    title: 'Automação de Fluxos',
    description: "This is an automated flow made with Power Automate to check on a daily basis if a release task was closed and, if true, send a notification to the product owners with an assessment form to respond. The form is made with MS Forms.",
    image: '/images/6.png',
    tags: ['PowerBI', 'Power Automate', 'MS Forms'],
    source: '',
    visit: '',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 1996, text: 'Início das minhas atividades em tecnologia como estagiário em provedor de internet', },
  { year: 1998, text: 'Atuando como administrador de servidor linux em empresa de hospedagem de páginas. Servidor web contratado no modelo Co-location', },
  { year: 2000, text: 'Atuando no suyporte a sistemas e a infraestrutura junto a empresa BeachPark Hotéis e Turismo', },
  { year: 2002, text: 'Atuando como analista de Ti  na empresa Construtora LM Ltda', },
  { year: 2003, text: 'Atuando como Coordenador de Tecnologia em Porto Freire Engenharia', },
  { year: 2006, text: 'Atuando como desenvolvedor e analista de requisitos na empresa federal Dataprev', },
  { year: 2012, text: 'Atuando como analista de sistemas junto ao Tribunal de Justiça do Ceará', },
  { year: 2023, text: 'Atuando como gestor na unidade de desenvolvimento dinâmico no Tribunal de Justiça do Ceará', },
];