export const projects = {
  en: [
    {
      title: 'React/CSS Gym Website',
      description: "Project based on React, CSS and a few libs. This project was deployed at Vercel. check it out, link below. React is a powerfull library and it uses JSX, a syntax extension to Javascript. JSX allows us to write HTML in React. JSX makes it easier to write and add HTML in React. The project is also complete responsive for mobile devices.",
      image: '/images/1.png',
      tags: ['CSS', 'React', 'Node', 'Javascript'],
      source: 'https://react-gym-ebon.vercel.app',
      visit: 'https://react-gym-ebon.vercel.app',
      id: 0,
    },
    {
      title: 'E-Commerce Bag Store',
      description: "E-Commerce site builted with React and Material UI. It also uses react hooks such as useState and useContext. It's a responsive site and can be used on different screen sizes. I used Eslint e Prettier on the dev environment setup for this project. CSS was used with styled-components.",
      image: '/images/2.png',
      tags: ['React', 'JavaScript', 'Material UI', 'Vite'],
      source: 'https://bag-store.vercel.app',
      visit: 'https://bag-store.vercel.app',
      id: 1,
    },
    {
      title: 'Hotel WebSite',
      description: "This is a hotel page example made with React, Next.js 13,  react-slick and react-popup. In this project, i used some features of Next.js 13 such as dynamic Routes and optimized Image component. I have added some animations on the first page with Framer-Motion.",
      image: '/images/4.png',
      tags: ['React', 'JavaScript', 'Next.js', 'Framer Motion'],
      source: 'https://golf-resort.vercel.app/',
      visit: 'https://golf-resort.vercel.app/',
      id: 2,
    },
    {
      title: 'Mobile App',
      description: "Mobile application developed in React Native for managing maintenance of residential or business assets. Built with the Expo framework. The basic version stores data locally in SQLite and includes report generation and a schedule with alerts for overdue maintenance.",
      image: '/images/3.png',
      tags: ['React Native', 'Expo Framework'],
      source: 'https://drive.google.com/file/d/1TPXl2J0kR1WPfh_f8JJhIN78uZoTqG4D/view',
      visit: 'https://drive.google.com/file/d/1TPXl2J0kR1WPfh_f8JJhIN78uZoTqG4D/view',
      id: 3,
    },
    {
      title: 'Low-Code/No-Code',
      description: "This is an app made with PowerApps Plataform. It use power automate flows to send notifications to its users. The data is stored on sharepoint lists. Also it has a dashboard panel developed on PowerBI and embbeded on the app.",
      image: '/images/5.png',
      tags: ['PowerApp', 'Power Automate', 'PowerBI'],
      source: '',
      visit: '',
      id: 4,
    },
    {
      title: 'Workflow Automation',
      description: "This is an automated flow made with Power Automate to check on a daily basis if a release task was closed and, if true, send a notification to the product owners with an assessment form to respond. The form is made with MS Forms.",
      image: '/images/6.png',
      tags: ['PowerBI', 'Power Automate', 'MS Forms'],
      source: '',
      visit: '',
      id: 5,
    },
  ],
  pt: [
    {
      title: 'Site de Academia React/CSS',
      description: "Projeto baseado em React, CSS e algumas bibliotecas. Este projeto foi implantado na Vercel. Confira, link abaixo. React é uma biblioteca poderosa que usa JSX, uma extensão de sintaxe para Javascript. JSX nos permite escrever HTML no React. JSX facilita a escrita e adição de HTML no React. O projeto também é completamente responsivo para dispositivos móveis.",
      image: '/images/1.png',
      tags: ['CSS', 'React', 'Node', 'Javascript'],
      source: 'https://react-gym-ebon.vercel.app',
      visit: 'https://react-gym-ebon.vercel.app',
      id: 0,
    },
    {
      title: 'Loja E-Commerce de Bolsas',
      description: "Site E-commerce construído com React e Material UI. Também usa hooks como useState e useContext. É um site responsivo que pode ser usado em diferentes tamanhos de tela. Usei Eslint e Prettier na configuração do ambiente de desenvolvimento para este projeto. CSS foi usado com styled-components.",
      image: '/images/2.png',
      tags: ['React', 'JavaScript', 'Material UI', 'Vite'],
      source: 'https://bag-store.vercel.app',
      visit: 'https://bag-store.vercel.app',
      id: 1,
    },
    {
      title: 'Site de Hotel',
      description: "Este é um exemplo de página de hotel feito com React, Next.js 13, react-slick e react-popup. Neste projeto, usei alguns recursos do Next.js 13 como rotas dinâmicas e componente de imagem otimizado. Adicionei algumas animações na primeira página com Framer-Motion.",
      image: '/images/4.png',
      tags: ['React', 'JavaScript', 'Next.js', 'Framer Motion'],
      source: 'https://golf-resort.vercel.app/',
      visit: 'https://golf-resort.vercel.app/',
      id: 2,
    },
    {
      title: 'Aplicativo móvel',
      description: "Aplicativo móvel desenvolvido em React Native para a gestão de manutenção de ativos de residência ou negócio. Desenvolvido com o framework Expo. A versão básica grava os dados localmente em SQLite. Possui funcionalidade de geração de relatórios e agenda com alertas de manutenções vencidas.",
      image: '/images/3.png',
      tags: ['React Native', 'Expo Framework'],
      source: 'https://drive.google.com/file/d/1TPXl2J0kR1WPfh_f8JJhIN78uZoTqG4D/view',
      visit: 'https://drive.google.com/file/d/1TPXl2J0kR1WPfh_f8JJhIN78uZoTqG4D/view',
      id: 3,
    },
    {
      title: 'Low-Code/No-Code',
      description: "Este é um aplicativo feito com a plataforma PowerApps. Usa fluxos do Power Automate para enviar notificações aos seus usuários. Os dados são armazenados em listas do SharePoint. Também possui um painel de dashboard desenvolvido no PowerBI e incorporado no aplicativo.",
      image: '/images/5.png',
      tags: ['PowerApp', 'Power Automate', 'PowerBI'],
      source: '',
      visit: '',
      id: 4,
    },
    {
      title: 'Automação de Fluxos',
      description: "Este é um fluxo automatizado feito com Power Automate para verificar diariamente se uma tarefa de release foi fechada e, se verdadeiro, enviar uma notificação aos proprietários do produto com um formulário de avaliação para responder. O formulário é feito com MS Forms.",
      image: '/images/6.png',
      tags: ['PowerBI', 'Power Automate', 'MS Forms'],
      source: '',
      visit: '',
      id: 5,
    },
  ],
};
